### ISSUE TITLE
Choose which services are shown

### ISSUE THREAD

**Issue by stefahn** [vonloxley/Shariff-Mediawiki#1]
Hi Niki,

first of all: Thanks for this extension.

In the file Shariff/shariff-backend/shariff.json I see a list of services. I assume it is where I can choose which services to show. 

However in Shariff/Shariff.php the services are hard coded (twitter, facebook, google+). It would be nice if the services are pulled from the json file. Is this possible?

Regards,
Stefan

**Comment by vonloxley** [comment]
Hi Stefan!

That should be no problem, (a bit of `json_decode` in `shariffLikeParserFunction_Render`). I’ll have a go at it next weekend.

**Comment by stefahn** [comment]
I checked the original docu at https://github.com/heiseonline/shariff-backend-php. The services list in shariff.json only says which services should get a counter. So I misunderstood it. 

I'm going with the original Shariff now. So no need to adapt your code ;)
