### ISSUE TITLE
No counters for Facebook and Twitter

### ISSUE THREAD

**Issue by stefahn** [vonloxley/Shariff-Mediawiki#2]
After setting my domain in Shariff/shariff-backend/shariff.json the google+ counter appears. But there are no counters for Facebook and Twitter. See this screenshot: http://awesomescreenshot.com/05c61a9t43

Tested it on 2 installs.

Update: Twitter counter are no longer available (see https://github.com/heiseonline/shariff-backend-php/issues/46). For the Facebook counter I am still investigating what the problem is.

**Comment by vonloxley** [comment]
Facebook works for me. No counters probably means a failure on the backend can yout try to ask the backend directly:
https://www.kochwiki.org/w/extensions/Shariff/shariff-backend/?url=https%3A%2F%2Fwww.kochwiki.org%2Fwiki%2FHauptseite
If the return is proper json everything should work, if it is null check your logs.

**Comment by vonloxley** [comment]
If your problem persists, please reopen with more info.
