### ISSUE TITLE
Support more Shariff features, e. g. language

### ISSUE THREAD

**Issue by krabina** [vonloxley/Shariff-Mediawiki#6]
The Shariff attribute "data-lang" is per default set to German "de". This can be changed by adding
`data-lange="en"`
into 
https://github.com/vonloxley/Shariff-Mediawiki/blob/d220040068bafa80f456b2ecb79e0d3772dbbbfc/Shariff.php#L39
(just before the data-backend-url...)

But this is a hack, as the script should read the MediaWiki language and set the correct one automatically.
Furthermore, it might be useful, to support further attributes...

**Comment by vonloxley** [comment]
Patches are welcome.
